import { SquareTypes } from "./Square";

export const EasyMaps: SquareTypes[][][] = [
    [
        [SquareTypes.Wall,SquareTypes.Wall,SquareTypes.Space,SquareTypes.Space,SquareTypes.Wall,SquareTypes.Space,SquareTypes.Wall,SquareTypes.Space],
        [SquareTypes.Space,SquareTypes.Wall,SquareTypes.Wall,SquareTypes.Wall,SquareTypes.Space,SquareTypes.Space,SquareTypes.Wall,SquareTypes.Wall],
        [SquareTypes.Wall,SquareTypes.Space,SquareTypes.Space,SquareTypes.Wall,SquareTypes.Wall,SquareTypes.Wall,SquareTypes.Space,SquareTypes.Space],
        [SquareTypes.Wall,SquareTypes.Wall,SquareTypes.Wall,SquareTypes.Wall,SquareTypes.Wall,SquareTypes.Wall,SquareTypes.Wall,SquareTypes.Wall],
        [SquareTypes.Wall,SquareTypes.Space,SquareTypes.Space,SquareTypes.Wall,SquareTypes.Wall,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space],
        [SquareTypes.Space,SquareTypes.Wall,SquareTypes.Wall,SquareTypes.Wall,SquareTypes.Space,SquareTypes.Space,SquareTypes.Wall,SquareTypes.Wall],
        [SquareTypes.Space,SquareTypes.Wall,SquareTypes.Space,SquareTypes.Space,SquareTypes.Wall,SquareTypes.Wall,SquareTypes.Space,SquareTypes.Wall],
        [SquareTypes.Wall,SquareTypes.Wall,SquareTypes.Space,SquareTypes.Wall,SquareTypes.Space,SquareTypes.Space,SquareTypes.Wall,SquareTypes.Goal]
    ],
    [
        [SquareTypes.Wall,SquareTypes.Space,SquareTypes.Wall,SquareTypes.Wall,SquareTypes.Wall,SquareTypes.Wall,SquareTypes.Space,SquareTypes.Wall],
        [SquareTypes.Space,SquareTypes.Space,SquareTypes.Wall,SquareTypes.Wall,SquareTypes.Space,SquareTypes.Wall,SquareTypes.Space,SquareTypes.Wall],
        [SquareTypes.Space,SquareTypes.Wall,SquareTypes.Wall,SquareTypes.Wall,SquareTypes.Wall,SquareTypes.Wall,SquareTypes.Wall,SquareTypes.Wall],
        [SquareTypes.Wall,SquareTypes.Wall,SquareTypes.Space,SquareTypes.Wall,SquareTypes.Wall,SquareTypes.Space,SquareTypes.Wall,SquareTypes.Space],
        [SquareTypes.Space,SquareTypes.Wall,SquareTypes.Wall,SquareTypes.Wall,SquareTypes.Space,SquareTypes.Wall,SquareTypes.Wall,SquareTypes.Space],
        [SquareTypes.Wall,SquareTypes.Space,SquareTypes.Wall,SquareTypes.Space,SquareTypes.Wall,SquareTypes.Wall,SquareTypes.Space,SquareTypes.Space],
        [SquareTypes.Wall,SquareTypes.Space,SquareTypes.Wall,SquareTypes.Wall,SquareTypes.Space,SquareTypes.Space,SquareTypes.Wall,SquareTypes.Wall],
        [SquareTypes.Space,SquareTypes.Wall,SquareTypes.Wall,SquareTypes.Wall,SquareTypes.Wall,SquareTypes.Wall,SquareTypes.Wall,SquareTypes.Goal]
    ],
    [
        [SquareTypes.Wall,SquareTypes.Space,SquareTypes.Wall,SquareTypes.Wall,SquareTypes.Space,SquareTypes.Wall,SquareTypes.Space,SquareTypes.Space],
        [SquareTypes.Space,SquareTypes.Wall,SquareTypes.Space,SquareTypes.Wall,SquareTypes.Space,SquareTypes.Space,SquareTypes.Wall,SquareTypes.Space],
        [SquareTypes.Wall,SquareTypes.Space,SquareTypes.Wall,SquareTypes.Wall,SquareTypes.Wall,SquareTypes.Wall,SquareTypes.Wall,SquareTypes.Space],
        [SquareTypes.Wall,SquareTypes.Wall,SquareTypes.Wall,SquareTypes.Space,SquareTypes.Space,SquareTypes.Wall,SquareTypes.Space,SquareTypes.Wall],
        [SquareTypes.Wall,SquareTypes.Wall,SquareTypes.Space,SquareTypes.Wall,SquareTypes.Wall,SquareTypes.Space,SquareTypes.Wall,SquareTypes.Wall],
        [SquareTypes.Space,SquareTypes.Wall,SquareTypes.Wall,SquareTypes.Space,SquareTypes.Wall,SquareTypes.Space,SquareTypes.Wall,SquareTypes.Space],
        [SquareTypes.Wall,SquareTypes.Wall,SquareTypes.Space,SquareTypes.Wall,SquareTypes.Wall,SquareTypes.Wall,SquareTypes.Space,SquareTypes.Space],
        [SquareTypes.Wall,SquareTypes.Space,SquareTypes.Wall,SquareTypes.Wall,SquareTypes.Space,SquareTypes.Wall,SquareTypes.Wall,SquareTypes.Goal]
    ]
];

export const MedMaps: SquareTypes[][][] = [
    [
        [SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space],
        [SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space],
        [SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space],
        [SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space],
        [SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space],
        [SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space],
        [SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space],
        [SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space],
        [SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space],
        [SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Goal]
    ],
    [
        [SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space],
        [SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space],
        [SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space],
        [SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space],
        [SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space],
        [SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space],
        [SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space],
        [SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space],
        [SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space],
        [SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Goal]
    ],
    [
        [SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space],
        [SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space],
        [SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space],
        [SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space],
        [SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space],
        [SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space],
        [SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space],
        [SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space],
        [SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space],
        [SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Goal]
    ]
];

export const HardMaps: SquareTypes[][][] = [
    [
        [SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space],
        [SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space],
        [SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space],
        [SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space],
        [SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space],
        [SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space],
        [SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space],
        [SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space],
        [SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space],
        [SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space],
        [SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space],
        [SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Goal]
    ],
    [
        [SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space],
        [SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space],
        [SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space],
        [SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space],
        [SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space],
        [SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space],
        [SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space],
        [SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space],
        [SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space],
        [SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space],
        [SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space],
        [SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Goal]
    ],
    [
        [SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space],
        [SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space],
        [SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space],
        [SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space],
        [SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space],
        [SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space],
        [SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space],
        [SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space],
        [SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space],
        [SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space],
        [SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space],
        [SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Space,SquareTypes.Goal]
    ]
];